// ============================================================
// songs.js — モック楽曲プール(Phase 4 スタブ)
// 本番では Spotify Web API + LLM タグ付けに差し替える。
// ここでは各曲に types(適合タイプ parody名) と genre を手付与。
// recommend() は type 適合 + ジャンル一致でスコアし、ランダム10曲を返す。
// fallback により、どのタイプでも必ず10曲そろう。
// ============================================================

// IS_MOCK: 楽曲選定はモック手動マッピングだが、データ取得は Spotify Web API + iTunes 併用で本物
// 「サンプル選曲」UI表記を出すかのフラグ
const IS_MOCK = false;

const SONGS = [
  { title: "Pretender", artist: "Official髭男dism", genre: "J-POP", types: ["沼っくま", "ロマンチスト", "情熱ラブゾンビ"] },
  { title: "怪獣の花唄", artist: "Vaundy", genre: "邦ロック", types: ["バイブス警察", "マブダチエイリアン", "ピュアエンジェル"] },
  { title: "シンデレラボーイ", artist: "Saucy Dog", genre: "邦ロック", types: ["一途ペンギン", "沼っくま", "ヤキモチモンスター"] },
  { title: "ドライフラワー", artist: "優里", genre: "バラード", types: ["沼っくま", "一途ペンギン", "ロマンチスト"] },
  { title: "ベテルギウス", artist: "優里", genre: "J-POP", types: ["運命マジシャン", "一途ペンギン", "ピュアエンジェル"] },
  { title: "炎", artist: "LiSA", genre: "アニソン", types: ["情熱ラブゾンビ", "一途ペンギン", "ド直球ザウルス"] },
  { title: "夜に駆ける", artist: "YOASOBI", genre: "ボカロ", types: ["運命マジシャン", "ときめきパパラッチ", "沼っくま"] },
  { title: "アイドル", artist: "YOASOBI", genre: "アニソン", types: ["推し活ベビー", "ときめきパパラッチ", "バイブス警察"] },
  { title: "ヒバナ", artist: "DECO*27", genre: "ボカロ", types: ["ヤキモチモンスター", "情熱ラブゾンビ", "沼っくま"] },
  { title: "可愛くてごめん", artist: "HoneyWorks", genre: "ボカロ", types: ["ときめきパパラッチ", "ピュアエンジェル", "推し活ベビー"] },
  { title: "ケセラセラ", artist: "Mrs. GREEN APPLE", genre: "J-POP", types: ["チル仙人", "ド直球ザウルス", "マブダチエイリアン"] },
  { title: "ライラック", artist: "Mrs. GREEN APPLE", genre: "邦ロック", types: ["バイブス警察", "ピュアエンジェル", "マブダチエイリアン"] },
  { title: "Subtitle", artist: "Official髭男dism", genre: "バラード", types: ["一途ペンギン", "ロマンチスト", "慎重うさぎ"] },
  { title: "新時代", artist: "Ado", genre: "J-POP", types: ["ド直球ザウルス", "バイブス警察", "情熱ラブゾンビ"] },
  { title: "唱", artist: "Ado", genre: "EDM/ダンス", types: ["ときめきパパラッチ", "バイブス警察", "ミステリアス狼"] },
  { title: "勝手にしやがれ", artist: "Tani Yuuki", genre: "アコースティック/弾き語り", types: ["一途ペンギン", "沼っくま", "慎重うさぎ"] },
  { title: "W/X/Y", artist: "Tani Yuuki", genre: "バラード", types: ["ヤキモチモンスター", "沼っくま", "情熱ラブゾンビ"] },
  { title: "115万キロのフィルム", artist: "Official髭男dism", genre: "バラード", types: ["ロマンチスト", "一途ペンギン", "運命マジシャン"] },
  { title: "Cry Baby", artist: "Official髭男dism", genre: "邦ロック", types: ["情熱ラブゾンビ", "バイブス警察", "マブダチエイリアン"] },
  { title: "祝福", artist: "YOASOBI", genre: "アニソン", types: ["ピュアエンジェル", "運命マジシャン", "ド直球ザウルス"] },
  { title: "サウダージ", artist: "ポルノグラフィティ", genre: "邦ロック", types: ["ミステリアス狼", "沼っくま", "情熱ラブゾンビ"] },
  { title: "366日", artist: "HY", genre: "バラード", types: ["一途ペンギン", "沼っくま", "ヤキモチモンスター"] },
  { title: "花束", artist: "back number", genre: "バラード", types: ["一途ペンギン", "ロマンチスト", "ピュアエンジェル"] },
  { title: "高嶺の花子さん", artist: "back number", genre: "J-POP", types: ["慎重うさぎ", "ピュアエンジェル", "マブダチエイリアン"] },
  { title: "ハッピーエンド", artist: "back number", genre: "バラード", types: ["沼っくま", "一途ペンギン", "慎重うさぎ"] },
  { title: "クリスマスソング", artist: "back number", genre: "J-POP", types: ["ロマンチスト", "ピュアエンジェル", "運命マジシャン"] },
  { title: "ヒロイン", artist: "back number", genre: "バラード", types: ["ロマンチスト", "一途ペンギン", "ヤキモチモンスター"] },
  { title: "君はロックを聴かない", artist: "あいみょん", genre: "邦ロック", types: ["マブダチエイリアン", "慎重うさぎ", "ピュアエンジェル"] },
  { title: "マリーゴールド", artist: "あいみょん", genre: "アコースティック/弾き語り", types: ["チル仙人", "ピュアエンジェル", "一途ペンギン"] },
  { title: "愛を伝えたいだとか", artist: "あいみょん", genre: "邦ロック", types: ["ド直球ザウルス", "情熱ラブゾンビ", "ピュアエンジェル"] },
  { title: "裸の心", artist: "あいみょん", genre: "バラード", types: ["慎重うさぎ", "一途ペンギン", "ピュアエンジェル"] },
  { title: "君という花", artist: "ASIAN KUNG-FU GENERATION", genre: "バンド", types: ["バイブス警察", "マブダチエイリアン", "ド直球ザウルス"] },
  { title: "天体観測", artist: "BUMP OF CHICKEN", genre: "バンド", types: ["同志予報士", "マブダチエイリアン", "運命マジシャン"] },
  { title: "なないろ", artist: "BUMP OF CHICKEN", genre: "J-POP", types: ["ピュアエンジェル", "同志予報士", "チル仙人"] },
  { title: "白日", artist: "King Gnu", genre: "邦ロック", types: ["ミステリアス狼", "沼っくま", "慎重うさぎ"] },
  { title: "一途", artist: "King Gnu", genre: "アニソン", types: ["一途ペンギン", "情熱ラブゾンビ", "ヤキモチモンスター"] },
  { title: "Vinyl", artist: "King Gnu", genre: "R&B", types: ["ミステリアス狼", "チル仙人", "沼っくま"] },
  { title: "Subway", artist: "Awesome City Club", genre: "シティポップ", types: ["チル仙人", "同志予報士", "マブダチエイリアン"] },
  { title: "勿忘", artist: "Awesome City Club", genre: "シティポップ", types: ["ロマンチスト", "沼っくま", "ミステリアス狼"] },
  { title: "Plastic Love", artist: "竹内まりや", genre: "シティポップ", types: ["ミステリアス狼", "ときめきパパラッチ", "沼っくま"] },
  { title: "真夜中のドア", artist: "松原みき", genre: "シティポップ", types: ["ミステリアス狼", "チル仙人", "ロマンチスト"] },
  { title: "Magic", artist: "藤井 風", genre: "R&B", types: ["チル仙人", "バイブス警察", "ピュアエンジェル"] },
  { title: "きらり", artist: "藤井 風", genre: "シティポップ", types: ["チル仙人", "マブダチエイリアン", "バイブス警察"] },
  { title: "死ぬのがいいわ", artist: "藤井 風", genre: "R&B", types: ["沼っくま", "情熱ラブゾンビ", "ヤキモチモンスター"] },
  { title: "ベテルギウス(inst)", artist: "Cafe BGM", genre: "クラシック/インスト", types: ["チル仙人", "慎重うさぎ", "ロマンチスト"] },
  { title: "Lover", artist: "Taylor Swift", genre: "洋楽ポップ", types: ["ロマンチスト", "一途ペンギン", "ピュアエンジェル"] },
  { title: "Cruel Summer", artist: "Taylor Swift", genre: "洋楽ポップ", types: ["ときめきパパラッチ", "沼っくま", "バイブス警察"] },
  { title: "As It Was", artist: "Harry Styles", genre: "洋楽ポップ", types: ["チル仙人", "ミステリアス狼", "マブダチエイリアン"] },
  { title: "Levitating", artist: "Dua Lipa", genre: "EDM/ダンス", types: ["ときめきパパラッチ", "バイブス警察", "ド直球ザウルス"] },
  { title: "Blinding Lights", artist: "The Weeknd", genre: "EDM/ダンス", types: ["ときめきパパラッチ", "ミステリアス狼", "情熱ラブゾンビ"] },
  { title: "Perfect", artist: "Ed Sheeran", genre: "洋楽ポップ", types: ["ロマンチスト", "運命マジシャン", "一途ペンギン"] },
  { title: "drivers license", artist: "Olivia Rodrigo", genre: "洋楽ポップ", types: ["沼っくま", "ヤキモチモンスター", "ロマンチスト"] },
  { title: "Dynamite", artist: "BTS", genre: "K-POP", types: ["バイブス警察", "ときめきパパラッチ", "推し活ベビー"] },
  { title: "Butter", artist: "BTS", genre: "K-POP", types: ["ド直球ザウルス", "ときめきパパラッチ", "情熱ラブゾンビ"] },
  { title: "LOVE DIVE", artist: "IVE", genre: "K-POP", types: ["ド直球ザウルス", "バイブス警察", "ミステリアス狼"] },
  { title: "Hype Boy", artist: "NewJeans", genre: "K-POP", types: ["ピュアエンジェル", "ときめきパパラッチ", "マブダチエイリアン"] },
  { title: "Ditto", artist: "NewJeans", genre: "K-POP", types: ["慎重うさぎ", "ピュアエンジェル", "沼っくま"] },
  { title: "アイラブユー", artist: "back number", genre: "バラード", types: ["ピュアエンジェル", "ド直球ザウルス", "一途ペンギン"] },
  { title: "ベイビーアイラブユーだぜ", artist: "サンプルバンド", genre: "アイドル", types: ["推し活ベビー", "ド直球ザウルス", "情熱ラブゾンビ"] },
  { title: "全力少年", artist: "スキマスイッチ", genre: "J-POP", types: ["マブダチエイリアン", "同志予報士", "ド直球ザウルス"] },
  { title: "奏", artist: "スキマスイッチ", genre: "バラード", types: ["一途ペンギン", "慎重うさぎ", "ロマンチスト"] },
  { title: "366歩のマーチ", artist: "サンプル合唱", genre: "アコースティック/弾き語り", types: ["同志予報士", "チル仙人", "推し活ベビー"] },
  { title: "Feel Special", artist: "TWICE", genre: "K-POP", types: ["推し活ベビー", "ピュアエンジェル", "ヤキモチモンスター"] },
  { title: "情熱大陸(inst)", artist: "葉加瀬太郎", genre: "クラシック/インスト", types: ["情熱ラブゾンビ", "同志予報士", "ド直球ザウルス"] },
  { title: "Lovin' you", artist: "サンプルソウル", genre: "ジャズ/ソウル", types: ["チル仙人", "ロマンチスト", "ミステリアス狼"] },
  { title: "君の知らない物語", artist: "supercell", genre: "アニソン", types: ["沼っくま", "ミステリアス狼", "一途ペンギン"] },
  { title: "secret base", artist: "ZONE", genre: "アイドル", types: ["マブダチエイリアン", "ピュアエンジェル", "運命マジシャン"] },
  { title: "ロキ", artist: "みきとP", genre: "ボカロ", types: ["ときめきパパラッチ", "バイブス警察", "推し活ベビー"] }
];
